import { t } from "@/lib/messages";

// Minecraftゲーム内言語リスト（公式Wiki準拠）
// native: ゲーム内表記、ja: 日本語名（native と同じ・冗長な場合は省略）
// 入力（Combobox）と表示（プロフィール等）の両方で共通利用する
type GameLanguageDef = {
  value: string;
  native: string;
  ja?: string;
};

const GAME_LANGUAGE_DEFS: GameLanguageDef[] = [
  { value: "af_za", native: "Afrikaans", ja: "アフリカーンス語" },
  { value: "ar_sa", native: "العربية", ja: "アラビア語" },
  { value: "ast_es", native: "Asturianu", ja: "アストゥリアス語" },
  { value: "az_az", native: "Azərbaycanca", ja: "アゼルバイジャン語" },
  { value: "ba_ru", native: "Башҡортса", ja: "バシキール語" },
  { value: "bar", native: "Boarisch", ja: "バイエルン語" },
  { value: "be_by", native: "Беларуская", ja: "ベラルーシ語" },
  { value: "bg_bg", native: "Български", ja: "ブルガリア語" },
  { value: "br_fr", native: "Brezhoneg", ja: "ブルトン語" },
  { value: "brb", native: "Brabants", ja: "ブラバント語" },
  { value: "bs_ba", native: "Bosanski", ja: "ボスニア語" },
  { value: "ca_es", native: "Català", ja: "カタルーニャ語" },
  { value: "cs_cz", native: "Čeština", ja: "チェコ語" },
  { value: "cy_gb", native: "Cymraeg", ja: "ウェールズ語" },
  { value: "da_dk", native: "Dansk", ja: "デンマーク語" },
  { value: "de_at", native: "Österreichisches Deutsch", ja: "ドイツ語（オーストリア）" },
  { value: "de_ch", native: "Schwiizerdütsch", ja: "スイスドイツ語" },
  { value: "de_de", native: "Deutsch", ja: "ドイツ語" },
  { value: "el_gr", native: "Ελληνικά", ja: "ギリシャ語" },
  { value: "en_au", native: "English (Australia)", ja: "英語" },
  { value: "en_ca", native: "English (Canada)", ja: "英語" },
  { value: "en_gb", native: "English (UK)", ja: "英語" },
  { value: "en_nz", native: "English (New Zealand)", ja: "英語" },
  { value: "en_pt", native: "Pirate Speak", ja: "海賊語" },
  { value: "en_ud", native: "ʇılƃuƎ (uʍop ǝpısdn)", ja: "逆さま英語" },
  { value: "en_us", native: "English (US)", ja: "英語" },
  { value: "enp", native: "Anglish", ja: "アングリッシュ" },
  { value: "enws", native: "Shakespearean English", ja: "シェイクスピア英語" },
  { value: "eo_uy", native: "Esperanto", ja: "エスペラント" },
  { value: "es_ar", native: "Español (Argentina)", ja: "スペイン語" },
  { value: "es_cl", native: "Español (Chile)", ja: "スペイン語" },
  { value: "es_ec", native: "Español (Ecuador)", ja: "スペイン語" },
  { value: "es_es", native: "Español (España)", ja: "スペイン語" },
  { value: "es_mx", native: "Español (México)", ja: "スペイン語" },
  { value: "es_uy", native: "Español (Uruguay)", ja: "スペイン語" },
  { value: "es_ve", native: "Español (Venezuela)", ja: "スペイン語" },
  { value: "esan", native: "Andaluz", ja: "アンダルシア語" },
  { value: "et_ee", native: "Eesti", ja: "エストニア語" },
  { value: "eu_es", native: "Euskara", ja: "バスク語" },
  { value: "fa_ir", native: "فارسی", ja: "ペルシア語" },
  { value: "fi_fi", native: "Suomi", ja: "フィンランド語" },
  { value: "fil_ph", native: "Filipino", ja: "フィリピン語" },
  { value: "fo_fo", native: "Føroyskt", ja: "フェロー語" },
  { value: "fr_ca", native: "Français (Canada)", ja: "フランス語" },
  { value: "fr_fr", native: "Français", ja: "フランス語" },
  { value: "fra_de", native: "Fränggisch", ja: "フランケン語" },
  { value: "fur_it", native: "Furlan", ja: "フリウリ語" },
  { value: "fy_nl", native: "Frysk", ja: "西フリジア語" },
  { value: "ga_ie", native: "Gaeilge", ja: "アイルランド語" },
  { value: "gd_gb", native: "Gàidhlig", ja: "スコットランド・ゲール語" },
  { value: "gl_es", native: "Galego", ja: "ガリシア語" },
  { value: "haw_us", native: "ʻŌlelo Hawaiʻi", ja: "ハワイ語" },
  { value: "he_il", native: "עברית", ja: "ヘブライ語" },
  { value: "hi_in", native: "हिन्दी", ja: "ヒンディー語" },
  { value: "hr_hr", native: "Hrvatski", ja: "クロアチア語" },
  { value: "hu_hu", native: "Magyar", ja: "ハンガリー語" },
  { value: "hy_am", native: "Հայերեն", ja: "アルメニア語" },
  { value: "id_id", native: "Bahasa Indonesia", ja: "インドネシア語" },
  { value: "ig_ng", native: "Igbo", ja: "イボ語" },
  { value: "io_en", native: "Ido", ja: "イド語" },
  { value: "is_is", native: "Íslenska", ja: "アイスランド語" },
  { value: "isv", native: "Interslavic", ja: "汎スラヴ語" },
  { value: "it_it", native: "Italiano", ja: "イタリア語" },
  { value: "ja_jp", native: t("common.langJaJp") },
  { value: "jbo_en", native: "la .lojban.", ja: "ロジバン" },
  { value: "ka_ge", native: "ქართული", ja: "ジョージア語" },
  { value: "kk_kz", native: "Қазақша", ja: "カザフ語" },
  { value: "kn_in", native: "ಕನ್ನಡ", ja: "カンナダ語" },
  { value: "ko_kr", native: "한국어", ja: "韓国語" },
  { value: "ksh", native: "Kölsch", ja: "ケルン語" },
  { value: "kw_gb", native: "Kernewek", ja: "コーンウォール語" },
  { value: "la_la", native: "Latina", ja: "ラテン語" },
  { value: "lb_lu", native: "Lëtzebuergesch", ja: "ルクセンブルク語" },
  { value: "li_li", native: "Limburgs", ja: "リンブルフ語" },
  { value: "lmo", native: "Lombard", ja: "ロンバルド語" },
  { value: "lo_la", native: "ລາວ", ja: "ラオス語" },
  { value: "lol_us", native: "LOLCAT" },
  { value: "lt_lt", native: "Lietuvių", ja: "リトアニア語" },
  { value: "lv_lv", native: "Latviešu", ja: "ラトビア語" },
  { value: "lzh", native: t("common.langLzh"), ja: "漢文" },
  { value: "mk_mk", native: "Македонски", ja: "マケドニア語" },
  { value: "mn_mn", native: "Монгол", ja: "モンゴル語" },
  { value: "ms_my", native: "Bahasa Melayu", ja: "マレー語" },
  { value: "mt_mt", native: "Malti", ja: "マルタ語" },
  { value: "nah", native: "Nāhuatl", ja: "ナワトル語" },
  { value: "nds_de", native: "Plattdüütsch", ja: "低地ドイツ語" },
  { value: "nl_be", native: "Vlaams", ja: "フラマン語" },
  { value: "nl_nl", native: "Nederlands", ja: "オランダ語" },
  { value: "nn_no", native: "Norsk Nynorsk", ja: "ノルウェー語（ニーノシュク）" },
  { value: "nb_no", native: "Norsk Bokmål", ja: "ノルウェー語（ブークモール）" },
  { value: "oc_fr", native: "Occitan", ja: "オック語" },
  { value: "ovd", native: "Övdalska", ja: "エルヴダーレン語" },
  { value: "pl_pl", native: "Polski", ja: "ポーランド語" },
  { value: "pt_br", native: "Português (Brasil)", ja: "ポルトガル語" },
  { value: "pt_pt", native: "Português (Portugal)", ja: "ポルトガル語" },
  { value: "qya_aa", native: "Quenya", ja: "クウェンヤ" },
  { value: "ro_ro", native: "Română", ja: "ルーマニア語" },
  { value: "rpr", native: "Русский (дореформенный)", ja: "ロシア語（旧正書法）" },
  { value: "ru_ru", native: "Русский", ja: "ロシア語" },
  { value: "ry_ua", native: "Руси|ьскый", ja: "ルシン語" },
  { value: "se_no", native: "Davvisámegiella", ja: "北部サーミ語" },
  { value: "sk_sk", native: "Slovenčina", ja: "スロバキア語" },
  { value: "sl_si", native: "Slovenščina", ja: "スロベニア語" },
  { value: "so_so", native: "Soomaali", ja: "ソマリ語" },
  { value: "sq_al", native: "Shqip", ja: "アルバニア語" },
  { value: "sr_cs", native: "Srpski (latinica)", ja: "セルビア語（ラテン文字）" },
  { value: "sr_sp", native: "Српски", ja: "セルビア語" },
  { value: "sv_se", native: "Svenska", ja: "スウェーデン語" },
  { value: "sxu", native: "Säggs'sch", ja: "ザクセン語" },
  { value: "szl", native: "Ślōnski", ja: "シレジア語" },
  { value: "ta_in", native: "தமிழ்", ja: "タミル語" },
  { value: "th_th", native: "ไทย", ja: "タイ語" },
  { value: "tl_ph", native: "Tagalog", ja: "タガログ語" },
  { value: "tlh_aa", native: "tlhIngan Hol", ja: "クリンゴン語" },
  { value: "tok", native: "toki pona", ja: "トキポナ" },
  { value: "tr_tr", native: "Türkçe", ja: "トルコ語" },
  { value: "tt_ru", native: "Татарча", ja: "タタール語" },
  { value: "uk_ua", native: "Українська", ja: "ウクライナ語" },
  { value: "val_es", native: "Valencià", ja: "バレンシア語" },
  { value: "vec_it", native: "Vèneto", ja: "ヴェネト語" },
  { value: "vi_vn", native: "Tiếng Việt", ja: "ベトナム語" },
  { value: "yi_de", native: "ייִדיש", ja: "イディッシュ語" },
  { value: "yo_ng", native: "Yorùbá", ja: "ヨルバ語" },
  { value: "zh_cn", native: t("common.langZhCn"), ja: "中国語（簡体字）" },
  { value: "zh_hk", native: t("common.langZhHk"), ja: "中国語（繁体字・香港）" },
  { value: "zh_tw", native: t("common.langZhTwTaiwan"), ja: "中国語（繁体字・台湾）" },
  { value: "zlm_arab", native: "بهاس ملايو (جاوي)", ja: "マレー語（ジャウィ文字）" },
];

/** ゲーム内表記に日本語名を併記した表示ラベルを構築する（例: "Svenska（スウェーデン語）"） */
function buildLanguageLabel(def: GameLanguageDef): string {
  return def.ja && def.ja !== def.native ? `${def.native}（${def.ja}）` : def.native;
}

export const GAME_LANGUAGE_OPTIONS = GAME_LANGUAGE_DEFS.map((def) => ({
  value: def.value,
  label: buildLanguageLabel(def),
}));

// 言語コード→Mapを構築（逆引き用）
const GAME_LANGUAGE_MAP = new Map(
  GAME_LANGUAGE_OPTIONS.map((opt) => [opt.value, opt.label])
);

/** 言語コードから表示名（日本語名併記）を取得する。未知のコードはそのまま返す */
export function getGameLanguageName(code: string): string {
  return GAME_LANGUAGE_MAP.get(code.toLowerCase()) ?? code;
}
