import { t } from "@/lib/messages";

// Minecraftゲーム内言語リスト（公式Wiki準拠）
// 入力（Combobox）と表示（プロフィール）の両方で共通利用する
export const GAME_LANGUAGE_OPTIONS = [
  { value: "af_za", label: "Afrikaans" },
  { value: "ar_sa", label: "العربية" },
  { value: "ast_es", label: "Asturianu" },
  { value: "az_az", label: "Azərbaycanca" },
  { value: "ba_ru", label: "Башҡортса" },
  { value: "bar", label: "Boarisch" },
  { value: "be_by", label: "Беларуская" },
  { value: "bg_bg", label: "Български" },
  { value: "br_fr", label: "Brezhoneg" },
  { value: "brb", label: "Brabants" },
  { value: "bs_ba", label: "Bosanski" },
  { value: "ca_es", label: "Català" },
  { value: "cs_cz", label: "Čeština" },
  { value: "cy_gb", label: "Cymraeg" },
  { value: "da_dk", label: "Dansk" },
  { value: "de_at", label: "Österreichisches Deutsch" },
  { value: "de_ch", label: "Schwiizerdütsch" },
  { value: "de_de", label: "Deutsch" },
  { value: "el_gr", label: "Ελληνικά" },
  { value: "en_au", label: "English (Australia)" },
  { value: "en_ca", label: "English (Canada)" },
  { value: "en_gb", label: "English (UK)" },
  { value: "en_nz", label: "English (New Zealand)" },
  { value: "en_pt", label: "Pirate Speak" },
  { value: "en_ud", label: "ʇılƃuƎ (uʍop ǝpısdn)" },
  { value: "en_us", label: "English (US)" },
  { value: "enp", label: "Anglish" },
  { value: "enws", label: "Shakespearean English" },
  { value: "eo_uy", label: "Esperanto" },
  { value: "es_ar", label: "Español (Argentina)" },
  { value: "es_cl", label: "Español (Chile)" },
  { value: "es_ec", label: "Español (Ecuador)" },
  { value: "es_es", label: "Español (España)" },
  { value: "es_mx", label: "Español (México)" },
  { value: "es_uy", label: "Español (Uruguay)" },
  { value: "es_ve", label: "Español (Venezuela)" },
  { value: "esan", label: "Andaluz" },
  { value: "et_ee", label: "Eesti" },
  { value: "eu_es", label: "Euskara" },
  { value: "fa_ir", label: "فارسی" },
  { value: "fi_fi", label: "Suomi" },
  { value: "fil_ph", label: "Filipino" },
  { value: "fo_fo", label: "Føroyskt" },
  { value: "fr_ca", label: "Français (Canada)" },
  { value: "fr_fr", label: "Français" },
  { value: "fra_de", label: "Fränggisch" },
  { value: "fur_it", label: "Furlan" },
  { value: "fy_nl", label: "Frysk" },
  { value: "ga_ie", label: "Gaeilge" },
  { value: "gd_gb", label: "Gàidhlig" },
  { value: "gl_es", label: "Galego" },
  { value: "haw_us", label: "ʻŌlelo Hawaiʻi" },
  { value: "he_il", label: "עברית" },
  { value: "hi_in", label: "हिन्दी" },
  { value: "hr_hr", label: "Hrvatski" },
  { value: "hu_hu", label: "Magyar" },
  { value: "hy_am", label: "Հայերեն" },
  { value: "id_id", label: "Bahasa Indonesia" },
  { value: "ig_ng", label: "Igbo" },
  { value: "io_en", label: "Ido" },
  { value: "is_is", label: "Íslenska" },
  { value: "isv", label: "Interslavic" },
  { value: "it_it", label: "Italiano" },
  { value: "ja_jp", label: t("common.langJaJp") },
  { value: "jbo_en", label: "la .lojban." },
  { value: "ka_ge", label: "ქართული" },
  { value: "kk_kz", label: "Қазақша" },
  { value: "kn_in", label: "ಕನ್ನಡ" },
  { value: "ko_kr", label: "한국어" },
  { value: "ksh", label: "Kölsch" },
  { value: "kw_gb", label: "Kernewek" },
  { value: "la_la", label: "Latina" },
  { value: "lb_lu", label: "Lëtzebuergesch" },
  { value: "li_li", label: "Limburgs" },
  { value: "lmo", label: "Lombard" },
  { value: "lo_la", label: "ລາວ" },
  { value: "lol_us", label: "LOLCAT" },
  { value: "lt_lt", label: "Lietuvių" },
  { value: "lv_lv", label: "Latviešu" },
  { value: "lzh", label: t("common.langLzh") },
  { value: "mk_mk", label: "Македонски" },
  { value: "mn_mn", label: "Монгол" },
  { value: "ms_my", label: "Bahasa Melayu" },
  { value: "mt_mt", label: "Malti" },
  { value: "nah", label: "Nāhuatl" },
  { value: "nds_de", label: "Plattdüütsch" },
  { value: "nl_be", label: "Vlaams" },
  { value: "nl_nl", label: "Nederlands" },
  { value: "nn_no", label: "Norsk Nynorsk" },
  { value: "nb_no", label: "Norsk Bokmål" },
  { value: "oc_fr", label: "Occitan" },
  { value: "ovd", label: "Övdalska" },
  { value: "pl_pl", label: "Polski" },
  { value: "pt_br", label: "Português (Brasil)" },
  { value: "pt_pt", label: "Português (Portugal)" },
  { value: "qya_aa", label: "Quenya" },
  { value: "ro_ro", label: "Română" },
  { value: "rpr", label: "Русский (дореформенный)" },
  { value: "ru_ru", label: "Русский" },
  { value: "ry_ua", label: "Руси|ьскый" },
  { value: "se_no", label: "Davvisámegiella" },
  { value: "sk_sk", label: "Slovenčina" },
  { value: "sl_si", label: "Slovenščina" },
  { value: "so_so", label: "Soomaali" },
  { value: "sq_al", label: "Shqip" },
  { value: "sr_cs", label: "Srpski (latinica)" },
  { value: "sr_sp", label: "Српски" },
  { value: "sv_se", label: "Svenska" },
  { value: "sxu", label: "Säggs'sch" },
  { value: "szl", label: "Ślōnski" },
  { value: "ta_in", label: "தமிழ்" },
  { value: "th_th", label: "ไทย" },
  { value: "tl_ph", label: "Tagalog" },
  { value: "tlh_aa", label: "tlhIngan Hol" },
  { value: "tok", label: "toki pona" },
  { value: "tr_tr", label: "Türkçe" },
  { value: "tt_ru", label: "Татарча" },
  { value: "uk_ua", label: "Українська" },
  { value: "val_es", label: "Valencià" },
  { value: "vec_it", label: "Vèneto" },
  { value: "vi_vn", label: "Tiếng Việt" },
  { value: "yi_de", label: "ייִדיש" },
  { value: "yo_ng", label: "Yorùbá" },
  { value: "zh_cn", label: t("common.langZhCn") },
  { value: "zh_hk", label: t("common.langZhHk") },
  { value: "zh_tw", label: t("common.langZhTwTaiwan") },
  { value: "zlm_arab", label: "بهاس ملايو (جاوي)" },
];

// 言語コード→Mapを構築（逆引き用）
const GAME_LANGUAGE_MAP = new Map(
  GAME_LANGUAGE_OPTIONS.map((opt) => [opt.value, opt.label])
);

/** 言語コードから表示名を取得する。未知のコードはそのまま返す */
export function getGameLanguageName(code: string): string {
  return GAME_LANGUAGE_MAP.get(code.toLowerCase()) ?? code;
}
